sopra-fs22-group-36/screw-your-neighbor-react

- src/api/api.ts
- src/components/routing/routers/AppRouter.tsx
- src/components/ui/CreateGame.tsx
- src/components/ui/RoomRow.tsx
- src/components/views/Game.tsx
- src/components/views/Lobby.tsx
- src/hooks/api/useCurrentGame.ts
- src/hooks/api/useGames.ts
- src/stores/AppStore.ts
- src/stores/CurrentGameStore.ts
- src/stores/GamesStore.ts
- src/styles/ui/Lists.scss
In a minimal manner with an ugly ui
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/45
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/46
> add functionality createGame, joinGame and leaveGame

- sonar-project.properties
- src/api/api.ts
- src/components/routing/routers/AppRouter.tsx
- src/components/ui/CreateGame.tsx
- src/components/ui/RoomRow.tsx
- src/components/views/Game.tsx
- src/components/views/Lobby.tsx
- src/hooks/api/useCurrentGame.ts
- src/hooks/api/useGames.ts
- src/stores/AppStore.ts
- src/stores/CurrentGameStore.ts
- src/stores/GamesStore.ts
- src/styles/ui/Lists.scss
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/86
> Feature exclude tests from converage

- src/components/views/Game.tsx
- src/components/views/Room.tsx
- src/hooks/api/useCurrentGame.ts
First implementation of playing a card by clicking on it, added a PATCH request to the room view
The GET /cards call will get outdated soon because of the bug fixes on the server-side, so it would be smart to merge the current changes.
> Game play card

- src/components/routing/routers/AppRouter.tsx
- src/components/ui/ControlPanel.tsx
- src/components/ui/RoomInfoContainer.tsx
- src/components/ui/RoomPlayerContainer.tsx
- src/components/views/Lobby.tsx
- src/components/views/Room.scss
- src/components/views/Room.tsx
- src/hooks/api/useCurrentGame.ts
- src/hooks/api/useGames.ts
- src/stores/CurrentGameStore.ts
- src/util/embedProxy.test.ts
- src/util/embedProxy.ts
https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/46
https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/47
> Functional Room View with updating Player-list

- src/App.tsx
- src/components/routing/guards/HttpsGuard.tsx
Inspired by https://github.com/mbasso/react-https-redirect
Issue: #40
> App: redirect to https if the domain is not localhost

- src/components/views/game/game/GameView.scss
- src/components/views/game/game/GameView.tsx
it's specified without BaseContainer.
> GameView: remove BaseContainer and adjust positioning

- README.md
- screw-your-neighbor-server-openapi.json
- src/components/views/game/game/scoreboard/ScoreBoard.scss
- src/components/views/game/game/scoreboard/ScoreBoard.tsx
> Feature first implementation of scoreboard

- src/components/routing/routers/AppRouter.tsx
- src/components/views/createplayer/CreatePlayer.tsx
- src/components/views/lobby/CreateGame.tsx
rename Register to CreatePlayer
Because that's what we do here.
CreatePlayer/CreateGame: allow submitting form with enter
closes #28
> Feature implement enter

- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/gametable/distributeOpponents.test.ts
- src/components/views/game/game/gametable/distributeOpponents.ts
- src/hooks/api/useCurrentGame.ts
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/139
> GameTable: distribute the hands of the opponents

- package-lock.json
- package.json
- src/components/views/game/game/videochat/VideoChat.scss
- src/components/views/game/game/videochat/VideoChat.tsx
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/123
> VideoChat: add simple integration of jitsi meet

- package-lock.json
- package.json
- src/components/views/lobby/Lobby.tsx
That new rooms don't just appear, but
Collapse -> expand into existence.
Use the collapse transition von material ui, because they already
implemented animations like it react-spring, which look
already cool.
> Lobby: add animation to roomlist

- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/scoreannouncing/ScoreAnnouncing.tsx
- src/components/views/game/game/scoreboard/ScoreBoard.tsx
In 4ff0cd1, adding the observer wrapper was forgotten.
The observer in YourHand will be made in #58
> game: add observers which were forgotten

- src/components/ui/CardComponent.tsx
- src/components/ui/HamburgerMenu.scss
- src/components/views/game/game/yourhand/YourHand.tsx
Im surprised it took this long for us to break the main - but now it should work again
> Feature remove unnecessary code

- src/components/views/game/game/scoreboard/ScoreBoard.scss
- src/components/views/game/game/scoreboard/ScoreBoard.tsx
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/58
> Feature continue with scoreboard

- src/components/ui/HamburgerMenu.scss
> Bugfix: You can now close the Hamburger Menu again

- src/components/ui/HamburgerMenu.scss
- src/components/ui/HamburgerMenu.tsx
Forgot to add these changes in the last pull request
> Hamburger: Style changes

- src/components/views/game/game/yourhand/YourHand.tsx
Now only the player whose turn it is, is able to play a card (serverside)
> Feature validate user card playing order

- src/components/ui/CardComponent.scss
- src/components/ui/CardComponent.tsx
- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/yourhand/YourHand.tsx
- src/hooks/api/useCurrentGame.ts
- src/stores/CurrentGameStore.ts
Ist mal ein erster Ansatz...kann definitiv noch verbessert werden. Es sind zwei issues in einem pull request. 
#70
#71
> Feature card playing animation

- src/components/ui/CardComponent.scss
- src/components/ui/CardComponent.tsx
- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/yourhand/YourHand.tsx
- src/hooks/api/useCurrentGame.ts
- src/stores/CurrentGameStore.ts
Reverts sopra-fs22-group-36/screw-your-neighbor-react#73
broke it 👎 
😢 
(whoops)
> Revert "Feature card playing animation"

- src/components/views/lobby/Lobby.tsx
Made sure that only the rooms that are still looking for players will show up in the lobby.
> Enhancement only show rooms in finding players

- src/components/routing/guards/GameGuard.tsx
That the users see the last card played.
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/154
> GameGuard: delay update to gameState.CLOSED

- src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
- src/hooks/api/useCurrentGame.ts
- src/stores/CurrentGameStore.ts
#99
Same process is already implemented in the backend.
> disable the number on the announcing board/modal

- src/stores/CurrentGameStore.ts
It did not work with 2 players (the button was still enabled).
> CurrentGameStore.ts: fix isLastPlayerAnnouncing

- package-lock.json
- package.json
- src/components/views/game/game/yourhand/YourHand.tsx
- src/components/views/lobby/Lobby.tsx
- src/styles/ui/Divs.scss
- src/styles/ui/Lists.scss
- src/styles/ui/images.scss
> Features: Scroll in Lobby view & Pop-up for inactive players

- screw-your-neighbor-server-openapi.json
- src/components/views/game/gamesummary/GameSummary.tsx
- src/hooks/api/useCurrentGame.ts
- src/hooks/api/useGames.ts
useGames.ts: fix redundant await on return sonarlint issue
https://sonarcloud.io/project/issues?issues=AYAt41whVQDk5xhgGXwG&open=AYAt41whVQDk5xhgGXwG&id=sopra-fs22-group-36_screw-your-neighbor-react
GameSummary: implement clickStartNewGame
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/154
Needs https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/pull/158
> Feature create join next game

- src/components/views/game/game/gametable/GameTable.scss
- src/components/views/game/game/gametable/GameTable.tsx
GameTable.scss: remove background color of card
We don't need it anymore because now we have beautiful pictures
of jass cards.
GameTable.tsx: inline method "method"
Because it does not do much, and the name does not describe what it does.
GameTable.tsx: add indicator that round was stacked
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/31
> Feature add stacked indicator

- package-lock.json
- package.json
- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/gametable/PlayerHand.scss
- src/components/views/game/game/gametable/PlayerHand.tsx
Use Player Icon instead of orange background.
Make the cards smaller that they somehow fit there.
Also show how many cards an opponent holds.
Noch bisschen ein draft, möchte noch eine animation hinzufügen, die die karte aus der gegner hand wegfliegen lässt
> PlayerHand: improve styling

- src/components/ui/HamburgerMenu.scss
- src/components/ui/HamburgerMenu.tsx
- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/gametable/PlayerHand.tsx
- src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
- src/components/views/game/game/scoreannouncing/LeaveButton.tsx
- There was a bug where leaving the game crashed the game, I fixed it but i feel like my implementation wasnt elegant - please check the changes in GameTable.tsx! 
- AnnouncementModal.tsx now has a functional LeaveGame button - the name of the player doesn't disappear from the "Announced tricks" list yet, but that can be fixed at in a later task
- Please let me know if i should add a "Rules" button to the announcement modal too - i thought it was a bit overkill but if you think it's necessary, just say so!
Issue: #80
> Feature leave during scoreannounce

- src/components/views/game/game/scoreannouncing/AnnouncementModal.scss
- src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
- src/components/views/game/game/videochat/VideoChat.scss
- src/components/views/game/game/videochat/VideoChat.tsx
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/12
> Feature overhaul jitsi meet

- LICENSE.txt
- README.md
Issue; https://github.com/sopra-fs22-group-36/screw-your-neighbor-server/issues/182
> add license

- src/components/views/joinGame/JoinGame.tsx
Added individual management for when a game the player was intived to is not available anymore.
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/122
> Management of players that want to join game that is not available anymore

- src/components/views/game/game/GameView.scss
- src/components/views/game/gamesummary/GameSummary.scss
- src/components/views/game/gamesummary/WinnersPodium.scss
- src/components/views/game/gamesummary/WinnersPodium.tsx
> GameSummary final touches

- src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
Issue: https://github.com/sopra-fs22-group-36/screw-your-neighbor-react/issues/140
> Assign Tooltip to Button in AnnouncementModal

- src/components/views/game/game/gametable/GameTable.tsx
- src/components/views/game/game/gametable/PlayerHand.tsx
- src/components/views/game/game/scoreannouncing/AnnouncementModal.tsx
- src/components/views/game/game/scoreboard/ScoreBoard.tsx
- src/components/views/game/game/yourhand/YourHand.tsx
- src/stores/CurrentGameStore.ts
Sometimes the frontend crashed when someone pressed start game,
because the state change was received, but somehow the game
had no matches.
Just to be sure and that we don't have a white when this happens.
> add null checks

- src/components/views/game/game/gametable/GameTable.scss
- src/components/views/game/game/gametable/GameTable.tsx
Also use info severity and reduce padding.
> GameTable: align alert again
